name: Terraform linting and validating

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: test-terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Intialize Terraform
        run: terraform init
        working-directory: src/terraform

      - name: Check lint
        run: terraform fmt -check -recursive
        working-directory: src/terraform

      - name: Validate Terraform
        run: terraform validate